#
# validate yml:
# circleci config validate
#
version: 2.1

#
# Orbs
#
orbs:
  tools: naturalcycles/tools@volatile

#
# Workflows
#
workflows:
  version: 2
  default-workflow:
    jobs:
      #      - tools/publish-job:
      #          filters:
      #            branches:
      #              only: master
      - tools/build-job
#      - tools/test-job
